#dataSource:
#  dbCreate: update
#  driverClassName: org.h2.Driver
#  logSql: true
#  loggingSql: true
#  password: sa
#  url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#  username: sa

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

#ribbon:
#  ServerListRefreshInterval: 1000

server:
  port: 8080

spring:
  application:
    name: helloDocker
