server:
  port: 8080
  servlet:
    #Spring Boot, by default, serves content on the root context path (“/”).
    context-path: /demoapp

spring:
  application:
    name: demoapp
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      dialect: H2
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""



endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

#ribbon:
#  ServerListRefreshInterval: 1000




