server:
  port: 8080
  servlet:
    #Spring Boot, by default, serves content on the root context path (“/”).
    context-path: /demoapp

spring:
  application:
    name: demoapp
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      dialect: H2
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  devtools:
    restart:
      exclude: static/**
#    remote:
#      debug:
#        local-port: 8010
      trigger-file: MainController.java

  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

#ribbon:
#  ServerListRefreshInterval: 1000

environments:
  dev:
    app:
      name: 'demoapp: springboot starter template app (dev profile)'
  prod:
    app:
      name: 'demoapp: springboot starter template app (prod profile)'


